{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodes",
    "label": "nodes",
    "query": {
     "query": "label_values(node_exporter_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://localhost:5000/available",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Buchungsübersicht",
   "type": "table",
   "description": "Hier werden die Buchungen der jeweiligen Rechner in einer Übersicht angezeigt. ",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://localhost:5000/status",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 5, "x": 18, "y": 0 },
   "options": {
    "content": "<a href=\"http://172.17.21.50:8000/index.php\" target=\"_blank\">\n    <div class=\"center-container\">\n        <button class=\"buchungsBtn\">\n            Buchungskalender\n        </button>\n    </div>\n</a>\n\n<style>\n/* Centering Container - Dynamic Height */\n.center-container {\n    padding: 0.75rem 0 0 0;\n    display: flex;\n    justify-content: center;  /* Horizontally center */\n    align-items: center;      /* Vertically center */\n    width: 100%;\n    min-height: 100%; /* Ensures the div grows dynamically based on the content */\n}\n\n/* Button Styling */\n.buchungsBtn {\n    background-color: transparent;\n    padding: 1rem 2rem;\n    font-size: 1.5rem;\n    color: #45a050;\n    border: 2px solid #45a050;\n    cursor: pointer;\n    border-radius: 0.5rem;\n    font-weight: normal;\n    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);\n    transition: background-color 0.3s ease, box-shadow 0.3s ease, transform 0.2s ease;\n}\n\n/* Hover Effect */\n.buchungsBtn:hover {\n    color: #1c1c1c;\n    background-color: #45a050;\n    font-weight: bolder;\n    box-shadow: 0 6px 10px rgba(0, 0, 0, 0.4);\n    transform: translateY(-2px);\n}\n</style>\n"
   },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "Current C02 emissions per day",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_smi_power_draw_instant_watts{instance=~\"$nodes\"}) * 343.96 / 1000 * 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstate",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "repeat": "nodes",
   "targets": [
    {
     "expr": "max(node_uname_info{instance=~\"$nodes\"}) by(instance, release, machine, version)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "repeat": "nodes",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$nodes\"} / node_memory_MemTotal_bytes{instance=~\"$nodes\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU-Util %",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "repeat": "nodes",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$nodes\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU-Utilization",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "repeat": "nodes",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(uuid) (nvidia_smi_utilization_gpu_ratio{instance=~\"$nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature overview",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "repeat": "nodes",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{instance=~\"$nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}